### ISSUE TITLE
We need a team.

### ISSUE THREAD

**Issue by TekhnaeRaav** [VoxelsKeep/VoxelsKeep#1]
Please see [minetest#515](https://github.com/minetest/minetest_game/issues/515) the latest comments by me

VoxelsKeep goal is to improve on minetest and make a game that can truly be fun. The game shall be run off of the community. We will give a goal for our contributors so that development can work faster. However, we need a team that can help manage the project.

I would like to mention some people that I believe to have similar ideals and are possible candidates for the organization. I would like the community opinions on this project(not just the people I mention).

@C1ffisme I've seen you fight valiantly for minetest :+1: 
@tobyplowy  I would love you to be are graphical artist.

(I may mention more people.)

 Also we are in special need of someone in knowledge of C++ that can manage and review the pulls and things of the engine. If anyone is experienced in C++ please speak up or mention this person.

I believe that the community can make something great if we come together. What do you say?

**Comment by tobyplowy** [comment]
thanks for letting me know about this :)
But I had the same idea as you did already 
I can help you guys but I will be very busy with my own project yes that's right me and some friends are making a minetest fork (but it will be a big one) 

We have music we have all the textures, (the textures and music are for promo matirial) now we are working on a website and soon we will announce the project (in just a copple more days)

It will be amazing :)

But to answer your question in a short way yes I can help but not all day every day :)

**Comment by Ferk** [comment]
Unless there's already a particular goal or new idea that isn't just "like MTG, but better", why not just join the team of one of the already existing third-party subgames loosely based on MTG, join forces and bring it up to date, rather than trying to make yet another separate small team to start yet another MTG-like subgame?

There's an entire subforum full of subgames released: https://forum.minetest.net/viewforum.php?f=15
And an even bigger one of subgames in development: https://forum.minetest.net/viewforum.php?f=50

**Comment by tobyplowy** [comment]
@Ferk well the project that I'm helping (I do the art related things) will be a better engine it will include but is not limited to
A better GUI, 
shaders and other graphical improvements
Even more optimisation (so that the engine can run on every computer at decent performance)
More customization for texture packs 
A good and very customisable mob api
Dimensions support (so you can add alternative Dimensions
A nice soundtrack
Developers that actually Give someting about Their community
And it will have a good playable game (without the need for mods to make it more fun) and we will also have officially supported mods that will add even more content
And much more

I don't know about you but that's a pretty great thing

**Comment by Ferk** [comment]
@tobyplowy I didn't mean your project, and honestly I didn't realize that the intent was to clone the engine and not just the game.

And of course I agree that it's a pretty great thing to have those things.

But to be honest, for what I've been following on minetest development, whenever there's a PR with a good implementation for a feature to the engine that does not break things it's typically accepted.

I wouldn't be surprised if many of the changes done in a fork of the engine were to be ported back to the original minetest project provided they have a good implementation (except for the inclusion of a full blown game).

**Comment by tobyplowy** [comment]
> I wouldn't be surprised if many of the changes done in a fork of the engine were to be ported back to the original minetest project

Yeh probably and I would be completely fine with that :)

> even if sometimes there might be lengthy discussions about implementation details.

Yeh and that's one of the big problems

**Comment by tobyplowy** [comment]
Also we should stay on topic becouse we are poluting this issue XD

**Comment by C1ffisme** [comment]
Oh hi!

I'm not sure who you can find that has adequate knowledge of C++ and is willing to start making a project from new code he may have never worked with before, but I'd like to see how far this goes...

My own skills as a C++ programmer are pretty limited, but I do know how to use the Lua API and I know how game balance works...

I'm not sure what else to say here, though...

**Comment by tobyplowy** [comment]
@TekhnaeRaav Why don't you join the team that I'm working with?
We already have a prittie good team and you know more poeple is nice :)

**Comment by TekhnaeRaav** [comment]
I had no Idea you were already doing this! That's great.
I would love to join you! Me and my team would be glad to help.
I know a bit about the Lua code now and tons of ideas.
And I'm sure @HarsulinsGhost and @zicklag could be a pretty good help and inspiration for the project.

So where is this project? Is it on github? Or a background WIP?
I'd love to know more.

**Comment by TekhnaeRaav** [comment]
he he, looks like this is more of getting a team to be on then getting a team to join ;)

**Comment by numberZero** [comment]
@tobyplowy That sounds very attractively =) I suppose you’re going to break compatibility with MT; that’s sad but that’s a must for normal development. MT has too much compatibility everywhere. I’d love to work on something more flexible and forward-looking. Just one question: is your fork friendly (i.e. LGPL’ed as MT itself)?

**Comment by HarsulinsGhost** [comment]
@tobyplowy I have a comment prepared to post on the Minetest discussion aimed at notifying other users of a better project to join. Say the word and give me the name of the project and I'll see if I might be able to gain some valuable additions to the team. Although I'd like to ask a little bit about your team's philosophy to be sure its in alignment with what I've already written. Mostly I just need to know that,
1: You have a plan and set goals in mind, and
2: You are more community driven team

**Comment by tobyplowy** [comment]
i have truble to answer the above questions in a correct way so i will ask scarecrowman 
(hes the derection leed at the moment) to explain for you guys (hes way better than me at that)

also thanks for the intrest it means alot to me

**Comment by tobyplowy** [comment]
well i will give some short answers but scere will give the real explanation :D

> That sounds very attractively =)

yes it does XD

> that’s sad but that’s a must for normal development

yeh true especially in the beginning

> friendly (i.e. LGPL’ed as MT itself)?

yes 

> I have a comment prepared to post on the Minetest discussion aimed at notifying other users 

yes thats amazing we also have that alredy :D

> Say the word and give me the name of the project

the 5th of feb this year will be the anouncement date and its called minecore

> I might be able to gain some valuable additions to the team. 

amazing thanks :D

> 1: You have a plan and set goals in mind, and

yes there is scere will explain in detail

> 2: You are more community driven team

yes we are for sure thats the whole point

**Comment by Scarecr0wman** [comment]
Hey everyone. Scarecröwman here. 

We basically want what everyone else wants... a pro-studio quality version of a Mining Sandbox that puts the creative power into the hands of community and the user-base. 

There are many many loose ends that must be tied up in order to have a decent starting platform for our project. This means we've been talking a lot about how our engine will be refined in order to focus on customization by creators and developers while seamlessly allowing for gameplay and gameplay functions.

Our first objective will be to clean up the sourcecode of Minetest. Which means lots of re-scheming, renaming and removing of unnessisary elements. Included in this phase is simple optimization techniques aimed at greatly reducing CPU and Video workload. Our intention is to preserve compatibiliy but we are willing to break compatibility for the sake of optimization and improvements. 
Target platforms from the start will include support for Linux and Windows, *(both 32 and 64 bit,) but our objective is to reach all PC platforms like mac and mobile like Android platforms in the future.

From that point, our goal will be to get the engine to a solid barebones system that gets all the functions creators could hope for when building and modding for their games. This includes but is not limited to the goals of: Voxel-based modelling, Custom Dimensions, A Quality, Flexible Mob API focused on Optimization, Emphasis on Immersion and Graphical Atmosphere, such as detailed shaders like colored lighting, -as well as intuitive techniques such as LOD, (Level of Detail)
. 
In addition we have plans for a fully playable base game complete with storylines, three dimensions, quality sounds and music, mobs and npcs, and much other content serving as examples for every usable function available in the engine. This will be in place so that when development enters its final stage, the focus will shift from developing the engine to developing mods for the engine.

Also we are very heavily considering the possibility of manufacturing official creation software to work alongside the engine. These would be used for customization and mods, such as dimension creation, mobs and storyline workshop for beginning users unfamiliar with high-level programming, who still want to create decent mods.

Due to our policy concerning a Dev-Team to User-Base Communication doorway, our objective is to heavily consider all suggestions, without bias, (except in the case that quality would be compromised,) and to implement any code or content created by users that would make this engine a better piece of software.

That's about the gist of it.
I have more answers for anybody who have questions.

**Comment by tobyplowy** [comment]
and here is the github page https://github.com/MinecoreDevTeam

**Comment by Scarecr0wman** [comment]
We already have quality music even. Here is our Demo playlist.
https://soundcloud.com/scarecr0wman/sets/tracks-for-an-open-source

**Comment by Scarecr0wman** [comment]
![screenshot_20180201_165142](https://user-images.githubusercontent.com/34191066/35708060-e39b05e6-0771-11e8-96f0-3a862df31ddd.png)
![screenshot_20180201_165150](https://user-images.githubusercontent.com/34191066/35708062-e3b06800-0771-11e8-8718-203ceeb1fc10.png)
![screenshot_20180201_165256](https://user-images.githubusercontent.com/34191066/35708063-e3c7d1ac-0771-11e8-9cdf-baf30e2165ee.png)
![screenshot_20180201_165329](https://user-images.githubusercontent.com/34191066/35708064-e3dac618-0771-11e8-85f0-271d8ecacb97.png)

**Comment by tobyplowy** [comment]
and here are 2 landscape images :3
![image](https://user-images.githubusercontent.com/16853304/35708085-b26f5072-07ac-11e8-888b-ba9fcd42f399.png)
![image](https://user-images.githubusercontent.com/16853304/35708089-b79f1140-07ac-11e8-8b11-7e1e7bf1f336.png)

**Comment by TekhnaeRaav** [comment]
Very Nice!
I like the logo a lot to. 
This will be great.

**Comment by tobyplowy** [comment]
@TekhnaeRaav thanks yes it will be amazing and we have only just started it will only get better when we get more poeple and a community of our own

**Comment by tobyplowy** [comment]
also keep it silent until the 5th of feb so we have a great first anouncement :D

**Comment by TekhnaeRaav** [comment]
My lips are sealed.. :zipper_mouth_face:

**Comment by Scarecr0wman** [comment]
![screenshot_20180201_170859](https://user-images.githubusercontent.com/34191066/35708223-b83246a2-0772-11e8-8c97-d3c447db7058.png)

These textures are all 100% made from scratch by the way.

**Comment by numberZero** [comment]
Nice textures)
By the way, where is the repo of the game itself?

**Comment by tobyplowy** [comment]
@numberZero no not yet we will when we announce 
We are trying to recruit poeple first aswell :)

**Comment by tobyplowy** [comment]
@numberZero this is the engine https://github.com/MinecoreDevTeam/Engine
that will power everyting, if you whant you can open up an issue or a pr its more than welcome :D

**Comment by Scarecr0wman** [comment]
@numberZero In all honesty, our level of expertise is mainly in the areas of Art, audio design, visual design, concepts and quality execution. When it comes to the technical side of things, we are lagging behind to say the least. We are really looking for anyone and all who can help, but programmers are going to complete what holes we have left that we cannot fill.

**Comment by tobyplowy** [comment]
also does anyone here have a discord?

**Comment by HarsulinsGhost** [comment]
Alright! This feels good. I will eagerly await Feb. 5th for an epic reveal!

**Comment by Scarecr0wman** [comment]
We really are interested in anyone who can program who would be interested in joining our official development team. Let us know: lanterngaming.devteam@gmail.com

**Comment by HarsulinsGhost** [comment]
Just out of curiosity, what sort of music development tools do you guys use?

**Comment by Scarecr0wman** [comment]
I use a combination of software. I have used Garageband and FL Studio in the past. Now I'm using Ableton Live with Arturia sounds. Also I use Audacity for mastering.

**Comment by Scarecr0wman** [comment]
@TekhnaeRaav 
@HarsulinsGhost 
@numberZero

By the way guys, if any of you are interested in getting involved in conversations or what we're doing, you can enter our Discord server at this link: https://discord.gg/aXW8zwT

Even if you don't contribute to the project it still would mean a lot to us if you say hi and offer any suggestions. Plus you'll get an open door to seeing the progress in real-time. 

Can't wait to hear from you all. 

-Scare

**Comment by numberZero** [comment]
Discord? Er, what's that good in that yet another proprietary crap?

**Comment by tobyplowy** [comment]
@numberZero I don't really understand what you're saying :/

Are you saying that discord is bad?

**Comment by TekhnaeRaav** [comment]
Sorry, @tobyplowy, @Scarecr0wman, we won't be able to work with discord due to computer restrictions.

**Comment by tobyplowy** [comment]
@TekhnaeRaav how about gitter (we can set up a gitter if you guys whant that)

**Comment by tobyplowy** [comment]
@TekhnaeRaav bdw you can use discord on your browser you dount need to download anyting

**Comment by Scarecr0wman** [comment]
@numberZero @TekhnaeRaav 

We just like to talk over voice-chat. My philosophy is, if I'm not paying anything and just using their free services, I'm not really condoning proprietaries. It's actually a very useful tool.

**Comment by TekhnaeRaav** [comment]
To be honest with you guys, I'm using a computer that's locked down for only certain websites with my team. And discord can't be allowed.
    Although for simply background text chat I'm good with using Flock.

**Comment by Scarecr0wman** [comment]
Hey guys, just a heads up. We pushed our official first announcement on the minetest forums.
You know our situation but this will give you more in-depth details.
https://forum.minetest.net/viewtopic.php?f=14&t=19597

It will also be going on other places around the web. Much more to come!

**Comment by TekhnaeRaav** [comment]
Yay! looks like were about ready to clear this repo!
Can't wait to get started on Minecore!

**Comment by tobyplowy** [comment]
can you guys use this for chatting?
https://gitter.im/minecoredev/Lobby
keep in mind that evreyone is on discord so it may be very silent on gitter

**Comment by tobyplowy** [comment]
if you have any issues or prs for minecore feel free to let us know :D

**Comment by HarsulinsGhost** [comment]
Where would be the best spot for me to direct interested Minetest users to get info on Minecore? Is the Minecore website up or should I link to somewhere else?

**Comment by tobyplowy** [comment]
@HarsulinsGhost the minecore websit is not done jey but it shuld be tommorow (if everyting gos to plan)

> or should I link to somewhere else

i think the forum post is the best idea
https://forum.minetest.net/viewtopic.php?f=14&t=19597

**Comment by tobyplowy** [comment]
@TekhnaeRaav @HarsulinsGhost @zicklag 
we also have an email so if you whant you can contact us that way
lanterngaming.devteam@gmail.com

**Comment by TekhnaeRaav** [comment]
I _might_ be on the chats sometimes, but not often.

>we also have an email so if you whant you can contact us that way

That goes for you to:+1: Thanks.
